name: Android CI

on:
  pull_request:
    branches: [ main , develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode google-services.json
      env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo $GOOGLE_SERVICE_JSON > app/google-services.json
    - name: Access local.propeties
      env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      run: echo $LOCAL_PROPERTIES > local.properties
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Test with Gradle
      run: ./gradlew test
    - name: Build result to slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_WEBHOOK_URL }} 
      if: always()

