name: Android CI

on:

  pull_request:
    branches: [ main , develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode google-services.json
      env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo $GOOGLE_SERVICE_JSON > app/google-services.json
    - name: Access TTB_KEY
      env:
        TTB_KEY: ${{ secrets.TTB_KEY }}
      run: echo ttb_key=$TTB_KEY > ./local.properties
    - name: Access KAKAO_BASE_URL
      env:
        KAKAO_BASE_URL: ${{ secrets.KAKAO_BASE_URL }}
      run: echo kakao_base_url=$KAKAO_BASE_URL >> ./local.properties
    - name: Access ALADIN_BASE_URL
      env:
        ALADIN_BASE_URL: ${{ secrets.ALADIN_BASE_URL }}
      run: echo aladin_base_url=$KEY_PASS >> ./local.properties
    - name: Build with Gradle
      run: ./gradlew build -x test --stacktrace
    - name: Build result to slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_WEBHOOK_URL }} 
      if: always()

